name: irrigation_app_v2
description: "Um sistema de irrigação inteligente."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Pacotes do Firebase (Essencial para autenticação e banco de dados)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # Pacote para fazer chamadas de API (Comunicação com a AWS)
  http: ^1.2.1

  # Pacote para gestão de estado simplificada
  provider: ^6.1.2

  # Ícones padrão
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true