// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEsk4jopIzEYKF1F8EPuMTYjD1v6DuOA',
    appId: '1:136328659744:web:fc54e662aca2d22f9a4d45',
    messagingSenderId: '136328659744',
    projectId: 'sistema-irrigacao-inteligente',
    authDomain: 'sistema-irrigacao-inteligente.firebaseapp.com',
    storageBucket: 'sistema-irrigacao-inteligente.firebasestorage.app',
    measurementId: 'G-EHEYG04E8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jpxU_YBoVORhdF4-X-kUQI_iyLn7VnQ',
    appId: '1:136328659744:android:975557094469e79b9a4d45',
    messagingSenderId: '136328659744',
    projectId: 'sistema-irrigacao-inteligente',
    storageBucket: 'sistema-irrigacao-inteligente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlI-BDSdfTPFqFWuOOPqL-iW4Dv40V2FE',
    appId: '1:136328659744:ios:5e7968838c7706339a4d45',
    messagingSenderId: '136328659744',
    projectId: 'sistema-irrigacao-inteligente',
    storageBucket: 'sistema-irrigacao-inteligente.firebasestorage.app',
    iosBundleId: 'com.example.irrigationAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlI-BDSdfTPFqFWuOOPqL-iW4Dv40V2FE',
    appId: '1:136328659744:ios:5e7968838c7706339a4d45',
    messagingSenderId: '136328659744',
    projectId: 'sistema-irrigacao-inteligente',
    storageBucket: 'sistema-irrigacao-inteligente.firebasestorage.app',
    iosBundleId: 'com.example.irrigationAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXEsk4jopIzEYKF1F8EPuMTYjD1v6DuOA',
    appId: '1:136328659744:web:95652a47eb1e52589a4d45',
    messagingSenderId: '136328659744',
    projectId: 'sistema-irrigacao-inteligente',
    authDomain: 'sistema-irrigacao-inteligente.firebaseapp.com',
    storageBucket: 'sistema-irrigacao-inteligente.firebasestorage.app',
    measurementId: 'G-TME035ZDGH',
  );
}
